"use client";
import Container from "@/components/layout/Container";
import Button from "@/components/ui/Button";
import { company, heroFeatures } from "@/content/variants/construction";
import { motion } from "framer-motion";
import { ExternalLink, HardHat } from "lucide-react";
import Image from "next/image";

export default function ConstructionHero() {
  return <section className="relative overflow-hidden bg-background"><div className="absolute inset-x-0 top-0 -z-10 h-[36rem] bg-gradient-to-b from-primary/10 to-transparent" /><Container className="py-20 sm:py-24"><div className="grid items-center gap-12 lg:grid-cols-[0.95fr_1.05fr]"><motion.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }}><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/25 bg-primary/10 px-4 py-2 text-sm font-semibold text-primary"><HardHat className="h-4 w-4" /> Demo koncept stavebného webu</div><p className="mb-5 text-sm font-semibold uppercase tracking-[0.28em] text-primary">Ukážka firemnej prezentácie</p><h1 className="max-w-2xl text-4xl font-bold leading-[1.04] tracking-tight text-foreground sm:text-5xl xl:text-[3.75rem]">Staviame domy a rekonštrukcie bez kompromisov.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted">Ukážka toho, ako môže moderný web prezentovať služby, pracovný postup a vizuálny štýl stavebnej spoločnosti.</p><div className="mt-9 flex flex-col gap-4 sm:flex-row"><Button href="#sluzby">Pozrieť ukážku</Button><a href="https://www.samuelzeliska.sk/#projekty" target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-button border border-border bg-surface px-6 py-3 font-semibold text-foreground transition hover:-translate-y-0.5 hover:border-primary/50 hover:text-primary">Autor projektu <ExternalLink className="h-5 w-5" /></a></div><p className="mt-6 max-w-xl text-sm leading-6 text-muted">Fiktívny prezentačný obsah. Web neprijíma dopyty ani osobné údaje.</p></motion.div><motion.div initial={{ opacity: 0, scale: 0.97 }} animate={{ opacity: 1, scale: 1 }} className="overflow-hidden rounded-2xl border border-border bg-surface p-1.5 shadow-2xl"><div className="relative aspect-[16/10] overflow-hidden rounded-xl"><Image src={company.heroImage} alt="Ukážkový vizuál stavebného webu" fill sizes="(max-width: 1024px) 100vw, 52vw" priority className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/10 to-transparent" /><div className="absolute bottom-5 left-5 rounded-xl border border-white/15 bg-black/65 p-4 text-white backdrop-blur"><p className="text-xs uppercase tracking-wider text-primary">Demo prezentácia</p><p className="mt-1 font-semibold">Služby, proces a ukážkové vizualizácie</p></div></div></motion.div></div><div className="mt-10 grid gap-3 sm:grid-cols-3">{heroFeatures.map((item) => { const Icon = item.icon; return <div key={item.text} className="flex items-center gap-4 rounded-xl border border-border bg-surface px-5 py-4 text-sm font-medium text-muted"><span className="flex h-11 w-11 items-center justify-center rounded-lg bg-primary/10"><Icon className="h-5 w-5 text-primary" /></span>{item.text}</div>; })}</div></Container></section>;
}
